// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace TaskManagementApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260314191133_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TaskItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AssignedUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("DueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AssignedUserId");

                    b.HasIndex("TenantId");

                    b.ToTable("Tasks");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d907410e-5860-4cc4-8800-2230895c001f"),
                            AssignedUserId = new Guid("1b33930d-4437-41ee-9b10-a864b40cec78"),
                            Status = 0,
                            TenantId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Title = "Learn ASP.NET Core"
                        },
                        new
                        {
                            Id = new Guid("c534787f-dfb8-4269-8941-791efcb8c4e4"),
                            AssignedUserId = new Guid("bef81bfc-2cbb-4321-bd4a-cecb244dadcb"),
                            Status = 0,
                            TenantId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Title = "Build Web API"
                        });
                });

            modelBuilder.Entity("Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Tenants");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4da30340-fda0-49b0-b564-f511c630d221"),
                            Enabled = true,
                            Title = "Tenant-A"
                        },
                        new
                        {
                            Id = new Guid("2337e27f-58eb-4973-9b43-4b795dac1ad7"),
                            Enabled = true,
                            Title = "Tenant-B"
                        },
                        new
                        {
                            Id = new Guid("4da16ab8-3f6b-4af6-9fba-82daa779aeb9"),
                            Enabled = true,
                            Title = "Tenant-C"
                        });
                });

            modelBuilder.Entity("User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("bef81bfc-2cbb-4321-bd4a-cecb244dadcb"),
                            Email = "alice@tenant-a.example.com",
                            TenantId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Username = "alice"
                        },
                        new
                        {
                            Id = new Guid("657ca4fa-fb2d-4180-80db-1403c6b8579e"),
                            Email = "bob@tenant-a.example.com",
                            TenantId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Username = "bob"
                        },
                        new
                        {
                            Id = new Guid("1b33930d-4437-41ee-9b10-a864b40cec78"),
                            Email = "carol@tenant-b.example.com",
                            TenantId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Username = "carol"
                        },
                        new
                        {
                            Id = new Guid("420f5b2e-ef55-4733-8bd9-053a07b9ed9c"),
                            Email = "dan@tenant-b.example.com",
                            TenantId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Username = "dan"
                        },
                        new
                        {
                            Id = new Guid("eaa46a1d-7ace-4ba8-9b2e-a4e4f8d654d1"),
                            Email = "eve@tenant-c.example.com",
                            TenantId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Username = "eve"
                        },
                        new
                        {
                            Id = new Guid("13bac98c-abd2-424b-bf2f-e1c26dee0e71"),
                            Email = "frank@tenant-c.example.com",
                            TenantId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Username = "frank"
                        },
                        new
                        {
                            Id = new Guid("e8f46251-0c7a-47c2-99b3-88c9496d8e9d"),
                            Email = "grace@no-tenant.example.com",
                            TenantId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Username = "grace"
                        });
                });

            modelBuilder.Entity("UserTenant", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "TenantId");

                    b.HasIndex("TenantId");

                    b.ToTable("UserTenant");
                });

            modelBuilder.Entity("TaskItem", b =>
                {
                    b.HasOne("User", "AssignedUser")
                        .WithMany("Tasks")
                        .HasForeignKey("AssignedUserId");

                    b.Navigation("AssignedUser");
                });

            modelBuilder.Entity("UserTenant", b =>
                {
                    b.HasOne("Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("User", b =>
                {
                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
